### ISSUE TITLE
The original source code of the datasets

### ISSUE THREAD

**Issue by QiuJYWX** [spcl/ncc#29]
Dear authors,

Thanks for your kindly sharing of thie repo. The shared datasets are all LLVM IR files (https://polybox.ethz.ch/index.php/s/..). Would you please share the corresponding original source code of the datasets? If you can provide the scripts about how to convert the source code into the LLVM IR, that would be highly appreciated.

Kind regards,

**Comment by tbennun** [comment]
The dataset sources are publicly available source codes as listed [here](https://github.com/spcl/ncc/tree/master/data). To get the source code, simply browse to those projects and download the codes. 

We compiled the files from the original dataset sources using the `clang` compiler and the following flags: `-S -emit-llvm`. Trying to compile source files individually from the original code is not always simple (proper include folders need to be added for each file), so sometimes (e.g., in the Linux kernel) we modified the Makefile or configuration to add those flags. For example:

```sh
$ clang -S -emit-llvm file.cpp -o file.ll
```

In order to augment the training dataset, we also compile each file under different permutations of the available compiler flags we tested (-O0...-O3, fast math, etc.).

**Comment by LIANGKE23** [comment]
Hi,
Can you share the original C codes for these files?

**Comment by tbennun** [comment]
Unfortunately, I cannot share the source codes directly, as they need to be downloaded from the original sources due to licensing reasons. However, they should be straightforward to download from the project websites. Examples:
* TensorFlow - https://github.com/tensorflow/tensorflow
* AMD APP SDK - Not available through AMD but Googleable
* BLAS - https://github.com/xianyi/OpenBLAS
* Polybench GPU - http://www.cse.ohio-state.edu/~pouchet/software/polybench/download/polybench-gpu-1.0.tar.gz
* Rodinia - http://lava.cs.virginia.edu/Rodinia/download.htm
* SHOC - https://github.com/vetter/shoc
* Linux Kernel - https://github.com/torvalds/linux
* OpenCV - https://github.com/opencv/opencv
