### ISSUE TITLE
dictionary_pickle not available

### ISSUE THREAD

**Issue by nmustakin** [spcl/ncc#37]
I was trying to work with the pre-trained embeddings but was unable to do that since the dictionary_pickle file is not provided in the repository. I don't see a way to generate the dictionary without having to train the embeddings as well.

**Comment by nmustakin** [comment]
I found the issue. 
https://github.com/socal-ucr/ncc/blob/871239faa5f882db41caa3ed59f95e0795c3f324/task_utils.py#L38

This line defines the vocabulary directory as published_results/vocabulary when it should be data/vocabulary.

**Comment by tbennun** [comment]
Since the link to the dictionary file appears in the [published_results README](https://github.com/spcl/ncc/tree/master/published_results) (it is too large to store in the repository), that's where it is loaded from by default.

It seems that the server where the file is hosted is down at the moment, we are looking into this. Thanks for reporting!

**Comment by tbennun** [comment]
Just checked and the file is available online. Closing this issue for now. Please let us know if we should reopen.
